Readme.md
bower.json
gulpfile.js
package.json
tests/e2e/homepage.coffee
tests/karma.conf.js
tests/protractor.conf.js
tests/unit/controllers/main_controller_spec.coffee
tests/unit/controllers/mentor_controller_spec.coffee
tests/unit/services/mentor_spec.coffee

Adds unit testing using karma and jasmine, builds tests for all current controllers/services
To run unit tests, just run `gulp unit`

Add unit/e2e testing

---

.gitignore
app/index.html
app/js/app.coffee
app/js/controllers/mentor_controller.coffee
app/js/services/mentor.coffee
circle.yml
package.json
tests/karma.conf.js
tests/unit/controllers/mentor_controller_spec.coffee
tests/unit/services/mentor_spec.coffee

Connects frontend to the api. You can now add a mentor and it displays them.

Add api connection for mentor service and display on frontend

---

app/views/includes/sidebar.jade

Add links.

---

app/js/app.coffee
app/js/controllers/mentor_availability_controller.coffee
app/js/services/mentor_availability.coffee
app/views/includes/scripts.jade
app/views/includes/sidebar.jade
app/views/mentor-availability.jade
app/views/room-availability.jade

Add mentor availability page

---

app/js/app.coffee
app/js/controllers/submit_availability_controller.coffee
app/js/services/submit_availability.coffee
app/views/includes/scripts.jade
app/views/includes/sidebar.jade
app/views/submit-availability.jade

Add functionality to send calendars to submission url

---

app/index.jade
app/js/app.coffee
app/sass/main.scss
app/sass/partials/_makemeeting.scss
app/views/make-meeting.jade

Initialize make meeting and add details.

---

app/js/app.coffee
app/js/controllers/meeting_controller.coffee
app/js/services/attendee.coffee
app/js/services/meeting.coffee
app/sass/partials/_bootstrap_tweaks.scss
app/sass/partials/_makemeeting.scss
app/sass/partials/_vendor_overrides.scss
app/views/includes/scripts.jade
app/views/make-meeting.jade

Closes #44, Closes #45, Closes #46, Closes #50

First chunk of MVP functionality.

---

app/js/controllers/meeting_controller.coffee

Check input email against list of attendees.

---

app/js/controllers/meeting_controller.coffee
app/sass/partials/_makemeeting.scss
app/views/make-meeting.jade

Add meeting submission and form validation.

---

app/js/app.coffee
app/js/controllers/meeting_controller.coffee
app/sass/icotandem.scss
app/sass/main.scss
app/sass/partials/_success.scss
app/views/success.jade

Successful booking page.

---

app/views/make-meeting.jade

make invite email when you click the invite hyperlink

---

.gitignore
app/js/app.coffee
app/js/services/attendee.coffee
app/js/services/email.coffee
app/js/services/meeting.coffee
app/views/includes/scripts.jade
config/constants.js.sample
gulpfile.js

Add config file and move all constants to config

---

app/js/controllers/meeting_controller.coffee
app/views/make-meeting.jade

Add ability to send meeting length to backend

---

app/js/app.coffee
app/js/controllers/meeting_controller.coffee
app/views/includes/navigation.jade
app/views/includes/scripts.jade
app/views/login.jade
app/views/make-meeting.jade
app/views/success.jade
bower.json

add mixpanel integration and event tracking

---

app/views/success.jade

add links to social icons on success page

---

app/sass/partials/_success.scss
app/views/success.jade

Add feedback link to success page

---

app/views/make-meeting.jade

Closes #93 
When we implement #84 this will be a little more complicated as we'll want to take either a name or an email

Add basic validation to email form.

---

app/views/make-meeting.jade

Words are hard.

---

app/index.jade
app/js/app.coffee
app/js/controllers/login_controller.coffee
bower.json

Fix auth bug by using ui-router and removing run redirect

---

app/js/controllers/meeting_controller.coffee
app/sass/partials/_makemeeting.scss
app/views/make-meeting.jade
bower.json

Red borders on invalid fields / form sections.

---

app/js/controllers/meeting_controller.coffee
app/js/directives/selectable.coffee
app/sass/partials/_makemeeting.scss
app/views/make-meeting.jade
coffeelint.json
gulpfile.js

Add ability to choose specific meeting time with a popup modal

---

app/js/app.coffee
app/js/controllers/meeting_controller.coffee
app/js/controllers/success_controller.coffee
app/views/includes/scripts.jade
app/views/success.jade

Add event details to success page
